### PR TITLE
Clean-up xdt repository

### PR DESCRIPTION
**Pull request by ViktorHofer**
1. Delete unused or unnecessary files
2. Simplify msbuild logic
3. Simplify yml release branches and enable post build validation.
4. Upgrade repo version to 8.0.0
5. Add NETStandard.Library/2.0.3 package to avoid xunit bringing in the entire .NET Standard 1.x dependency graph.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@mmitche is this part still necessary? https://github.com/dotnet/xdt/blob/6ff9e0c9b97780e5015c505e51ba30672b3d1503/azure-pipelines.yml#L73-L85

**Comment by mmitche** [comment]
These lines are also not necessary: https://github.com/dotnet/xdt/pull/503/files#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5R18-R21

I would push to azdo and do an official build test.

**Comment by ViktorHofer** [comment]
Let me do that in a separate PR then.

**Comment by ViktorHofer** [comment]
cc @vijayrkn

**Review by mmitche — APPROVED** [review]

**Pull request merged**
