### PR TITLE
Update the servicing version for 3.1

### PR DESCRIPTION
**Pull request by vijayrkn**

### CODE REVIEW

**Comment by mmitche** [comment]
@MichaelSimons Can you ensure that the right source-build commits have made it into this?

**Comment by mmitche** [comment]
@vijayrkn We may want to port commits from main (except the 5.0 versioning update) back into 3.1. Maybe main should generally be archived if we aren't shipping a 5.0/6.0 version anyway.

**Comment by mmitche** [comment]
Hmmm. @MichaelSimons I assume that also requires updating to a 6.0 arcade?

Maybe an even better approach is to ship a 6.0 version of Xdt for this? We would need to get NuGet to update their referenced version though, since I think they're on 3.0.0

**Comment by vijayrkn** [comment]
Does main have all the required changes? Then we can use the build from Main and brand 6.0

**Comment by mmitche** [comment]
> Does main have all the required changes? Then we can use the build from Main and brand 6.0

It should. It's really only that commit that @MichaelSimons referenced, but that commit may depend on other arcade updates.

**Comment by MichaelSimons** [comment]
Yes, we would need 6.0 arcade.  Main has all of the source-build changes we need.

**Comment by mmitche** [comment]
My preferred method is to ship a 3.1.1 if possible, on that cherry-picked commit.

**Comment by mmitche** [comment]
> Yes, we would need 6.0 arcade. Main has all of the source-build changes we need.

Sounds good. Can you work with the NuGet folks to get their major version updated?

**Comment by MichaelSimons** [comment]
>Can you work with the NuGet folks to get their major version updated?

@mmitche - can you clarify who you are asking to work with the NuGet folks?  I'm unclear what the ask is about.

**Comment by mmitche** [comment]
> > Can you work with the NuGet folks to get their major version updated?
> 
> @mmitche - can you clarify who you are asking to work with the NuGet folks? I'm unclear what the ask is about.

- the SDK references 3.1.0, and we'll be updating that to a 6.0.0 version that will be shipped on NuGet.
- NuGet itself references 3.0.0. This might be okay, but when we update to 6.0.0 in the SDK, the major versions begin to differ, which doesn't sound like a good idea. Ideally both components would reference 6.0.0 going forward.

**Comment by MichaelSimons** [comment]
>NuGet itself references 3.0.0. This might be okay, but when we update to 6.0.0 in the SDK, the major versions begin to differ, which doesn't sound like a good idea. Ideally both components would reference 6.0.0 going forward.

That makes sense.  Yes I can reach out to them and ask them to upgrade.

**Comment by MichaelSimons** [comment]
>Is there an action item on me? I have created a new branch but I don't have any idea on what changes are needed.

This is the primary change we need released - https://github.com/dotnet/xdt/pull/352.  Aa Matt mentioned, this is going to need an updated arcade version as well.  I don't have any bandwidth to help.

**Pull request closed without merging**
